DIGITAL_ALL = "Digital all"
LIVE_ALL = "Live all"
MATERIAL = "Material"
LIVE = "Live"
DIGITAL = "Digital"
TEMP_EXT = ".yogad"
ALLURL = r"https://student.allendigital.in/JAIPUR/digital/Yogansh-Sharma?token="
BASE = r"https://student.allendigital.in"
LINK_SAVE_PATH = r"E:\bpms_links\data"
LOG_FILE = r"E:\bpms_links\log.txt"
COOKIE_PATH = r""
DIGITAL_SAVE_PATH = r"E:\bpms"
LIVE_SAVE_PATH = DIGITAL_SAVE_PATH
LIVE_URL = r"https://student.allendigital.in/JAIPUR/digitalliverecord/2020-2021/JAI4A643CC/Yogansh-Sharma?token="
DIGITAL_URL = r"https://student.allendigital.in/JAIPUR/digital/Yogansh-Sharma?token="
VIDEO_EXT = ".mp4"
MAT_EXT = ".pdf"
DIGITAL_MODULE_PATH = "https://student.allendigital.in/JAIPUR/player/2020-2021/JAI4A643CC/Yogansh-Sharma/"