MATERIAL = "Material"
LIVE = "live"
DIGITAL = "digital"
LIVE_URL = r"https://student.allendigital.in/JAIPUR/digitalliverecord/2020-2021/JAI4A643CC/Yogansh-Sharma?token="
DIGITAL_URL = r"https://student.allendigital.in/JAIPUR/digital/Yogansh-Sharma?token="
DIGITAL_MODULE_PATH = "https://student.allendigital.in/JAIPUR/player/2020-2021/JAI4A643CC/Yogansh-Sharma/"